### ISSUE TITLE
Use requirements.sh

### ISSUE THREAD

**Issue by MatthewScholefield** [tjoen/fallback-sarcasm#2]
This could have the `sudo apt-get install ...` line to automate the package installation on a Mark 1 / Picroft.

**Comment by tjoen** [comment]
Yep, That is much better indeed thanks.

**Comment by MatthewScholefield** [comment]
Nice! One other thing to note after testing it, to have it completely
automatic you might want to add the automatic yes flag, `-y`, which would
change it to: `sudo apt-get install -y ...`.

**Comment by tjoen** [comment]
Good point, I will change that too.
